language: node_js
node_js:
- '5'
addons:
  sauce_connect:
    no_ssl_bump_domains: all
  jwt:
    secure: 1ZzOyrKfHi1Kd2uXVXAZN9sPM9hUDSwBAnBvBfdu5kgYy2Q9GUidPh2iNqPJdnKkjzIamLBgWNahuZdiM6nYPZJ51LvXb1mU/wnWkqASNPHcLZ2EMQId3ORAm5I5hdZnmtU+Y7MAqkHe0lj7/tQsd0jte5u3eBLN9aZZLATvV9k=
script: gulp test:saucelabs
